version: '3'
services:
  inventory-service:
    build: ./inventory-service
    ports:
      - "5002:5002"
  shipping-service:
    build: ./shipping-service
    ports:
      - "5000:5000"
  users-service:
    build: ./users-service
    ports:
      - "5004:5004"
